### ISSUE TITLE
[BUG] Version 0.6.0 breaks pickaxe functionality

### ISSUE THREAD

**Issue by adozenlionsroaring** [LYIVX/LYIVXS-Furniture#2]
Just a heads up, the most recent version of the mod (0.6.0, released 2 March) breaks pickaxe functionality - all pickaxes now take a long time to break blocks, regardless of whether they have Efficiency V, are made of Netherite, etc. I verified this mod update was the source of the bug by downgrading to the old version (the problem went away).

**Comment by PotaterBoo** [comment]
Had the same problem and found that the mod didn't only break the pickaxe functionality, but also the axe functionality. While playing, I realised that Minecraft wasn't exactly 'Minecrafting' the way it should, as breaking logs of wood with an axe or stone with a pickaxe took about the same amount of time as it would have if I had used a fist or any other object in my inventory.

**Comment by LYIVX** [comment]
Thank you for your report ill get on that straight away, very weird though as nothing I have done should be affecting there functions 😂

**Comment by LYIVX** [comment]
> Just a heads up, the most recent version of the mod (0.6.0, released 2 March) breaks pickaxe functionality - all pickaxes now take a long time to break blocks, regardless of whether they have Efficiency V, are made of Netherite, etc. I verified this mod update was the source of the bug by downgrading to the old version (the problem went away).

Do you know if its all tools or just those two?

**Comment by LYIVX** [comment]
No worries i found the problem 😊

**Comment by DarvinVlad** [comment]
I confirm this problem

**Comment by adozenlionsroaring** [comment]
> > Just a heads up, the most recent version of the mod (0.6.0, released 2 March) breaks pickaxe functionality - all pickaxes now take a long time to break blocks, regardless of whether they have Efficiency V, are made of Netherite, etc. I verified this mod update was the source of the bug by downgrading to the old version (the problem went away).
> 
> Do you know if its all tools or just those two?

Just double-checked, hoes also appear to be broken. Shovels, however, seem to be okay.

**Comment by LYIVX** [comment]
> > > Just a heads up, the most recent version of the mod (0.6.0, released 2 March) breaks pickaxe functionality - all pickaxes now take a long time to break blocks, regardless of whether they have Efficiency V, are made of Netherite, etc. I verified this mod update was the source of the bug by downgrading to the old version (the problem went away).
> > 
> > 
> > Do you know if its all tools or just those two?
> 
> Just double-checked, hoes also appear to be broken. Shovels, however, seem to be okay.

Its All Fixed Now, Was A Problem With Geckolib Removing Minable Tags, So As A Temp Fix Ive Removed it, including The Microwave, Toaster And Kettle.
